import React, { createContext, useContext, useState, useEffect } from 'react';
import api from '../services/api';
import { AuthContext } from './AuthContext';

export const LanguageContext = createContext();

export const translations = {
  en: {
    
    ok: 'OK',
    dismiss: 'Got it',
    login: 'Login',
    register: 'Register',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save Changes',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    loading: 'Loading...',
    total: 'Total',
    quantity: 'Quantity',
    size: 'Size',
    remove: 'Remove',
    success: 'Success',
    error: 'Error',
    username: 'Username',
    email: 'Email',
    full_name: 'Full Name',
    phone: 'Phone',
    postal_code: 'Postal Code',
    
    
    auth_title_order: 'Sign In to Order',
    auth_msg_order: 'Please sign in or register to place an order.',
    auth_title_wish: 'Wishlist',
    auth_msg_wish: 'Please sign in or register to save to wishlist.',
    auth_title_comment: 'Post a Comment',
    auth_msg_comment: 'Please sign in to leave a review.',

    
    nav_home: 'Home',
    nav_products: 'Products',
    nav_categories: 'Categories',
    nav_price: 'Price',
    nav_brands: 'Brands',
    nav_product_types: 'Product Types',
    nav_recommended: 'Recommended',
    nav_newest: 'Newest Arrivals',
    nav_popular: 'Most Popular',
    nav_promo: 'Special Promo',
    nav_min: 'Min',
    nav_max: 'Max',
    nav_search_price: 'Filter by Price',
    nav_search_placeholder: 'Search products...',
    nav_no_found: 'No products found',
    nav_my_orders: 'My Orders',
    nav_login_reg: 'Login / Register',
    nav_profile: 'Account',
    nav_logout: 'Logout',
    nav_apparel: 'Apparel',
    nav_shoes: 'Shoes',
    nav_under_5k: 'Under 5,000',
    nav_above_50k: '50,000+',

    
    h_collection: 'COLLECTION',
    h_exclusive: 'EXCLUSIVE DROP',
    h_new_coll: 'NEW COLLECTION 2026',
    h_lookbook: 'THE LOOKBOOK 2026',
    h_lookbook_desc: 'A meticulous selection of rare finds and seasonal essentials. Redefining your style with every release.',
    h_buy_now: 'Buy Now',
    h_sold_out: 'Sold Out',
    h_shop_drop: 'Shop All Products',
    h_shop_now: 'Shop now',
    h_go_home: 'Go back to Home',
    h_exclusive_drop: 'EXCLUSIVE DROP',
    h_cactus_jack: 'CACTUS JACK\nTRAVIS SCOTT',
    h_ts_desc: 'The highly anticipated Air Jordan 1 Low OG WMNS "Olive" is here. Elevate your sneaker rotation.',
    h_new_coll_2026: 'NEW COLLECTION 2026',
    h_adidas_title: 'ADIDAS ORIGINALS\nCTT JACKET',
    h_adidas_desc: 'Experience the full spectrum of our latest drop. Premium fabrics in all essential tones.',
    h_items_left: 'items left',
    h_loading_exp: 'Loading Velin Experience...',
    h_out_of_stock: 'Out of Stock',

    
    ps_found: 'Found',
    ps_items: 'items',
    ps_filter_by: 'Filter By',
    ps_no_products: 'No products found at the moment.',
    ps_go_back: 'Back to Shop',
    ps_all_products: 'Shop All',
    ps_featured: 'FEATURED',
    ps_premium_coll: 'Premium Collection',
    ps_desc_nike: 'Nike was founded in 1964 by Bill Bowerman and Phil Knight as "Blue Ribbon Sports" before becoming Nike in 1971. With the iconic Swoosh logo and "Just Do It" slogan, Nike has become a global leader in sports footwear and apparel, blending innovation and fashion seamlessly.',
    ps_desc_adidas: 'Adidas, the German giant founded by Adolf "Adi" Dassler in 1949 with the vision to produce the best sports shoes for athletes. Over decades, Adidas has built the "Three Stripes" legacy and become the center of streetwear culture and the sports world.',
    ps_desc_stussy: 'Stussy, the legendary brand that truly defines "Streetwear", started in the early 80s by Shawn Stussy in Laguna Beach. From a brand for surfers to a global icon that perfectly blends hip-hop, punk, and high-fashion style.',
    ps_desc_new_balance: 'New Balance was established in 1906, starting with the production of arch supports in Boston before rising to a global footwear brand known for comfort, meticulous quality, and the "Dad Shoes" design that became a worldwide trend.',
    ps_desc_asics: 'Asics was founded in 1949 by Kihachiro Onitsuka under the name Onitsuka Tiger, with the belief "Anima Sana In Corpore Sano" (A Sound Mind in a Sound Body). Asics focuses on engineering excellence for footwear to unlock athletes\' highest potential.',
    ps_desc_converse: 'Converse, founded in 1908, created a new legend in 1917 with the Chuck Taylor All-Star basketball shoe. With a timeless classic design, Converse has become a genuine symbol of street fashion, pop-punk music, and self-expression.',
    ps_desc_puma: 'Puma, founded by Rudolf Dassler in 1948 in Germany, built global fame through fast innovation and collaborations with many global icons, perfectly blending the sport lifestyle with modern fashion.',
    ps_desc_default: 'VELIN curates the finest quality products from top brands worldwide, allowing you to experience outstanding style and the latest innovations across all fashion categories, whether footwear, apparel, or accessories that reflect your true self.',

    
    pd_available_sizes: 'Available Sizes',
    pd_selected: 'Selected',
    pd_available_colors: 'Available Colors',
    pd_quantity: 'Quantity',
    pd_add_to_cart: 'Add to Cart',
    pd_select_size: 'Select Size',
    pd_details: 'Product Details',
    pd_reviews: 'Reviews',
    pd_all_reviews: 'Total Reviews',
    pd_no_desc: 'No description available.',
    pd_no_reviews: 'No reviews yet.',
    pd_write_review: 'Write a Review',
    pd_shipping_info: 'Shipping Information',
    pd_auth_required: 'Login Required',
    pd_auth_msg: 'Please login to add items to your cart.',
    pd_back: 'Back',
    pd_in_stock: 'In Stock',
    pd_code: 'Code',
    pd_category: 'Category',
    pd_items_unit: 'items',
    pd_not_found: 'Product not found',
    pd_stock_limit: 'Quantity exceeds stock',
    pd_rate_error: 'Please rate before submitting',
    pd_comment_success: 'Comment submitted successfully!',

    
    cart_title: 'Your Cart',
    cart_empty: 'Your cart is empty',
    cart_go_shop: 'Go Shopping',
    cart_summary: 'Order Summary',
    cart_subtotal: 'Subtotal',
    cart_discount: 'Product Discount',
    cart_shipping: 'Shipping',
    cart_free: 'FREE',
    cart_total: 'Total Amount',
    cart_checkout: 'Proceed to Checkout',
    cart_added: 'Added to cart',
    cart_add_success: 'Added to cart!',
    cart_remove_success: 'Removed from cart',
    
    
    wish_added: 'Added to wishlist!',
    wish_removed: 'Removed from wishlist',
    wish_subtitle: 'Items you are interested in and saved.',
    wish_empty: 'No items in wishlist',
    wish_empty_desc: 'Go back and browse products you like and save them here.',

    
    ord_title: 'Order History',
    ord_number: 'Order',
    ord_date: 'Date',
    ord_status: 'Status',
    ord_total: 'Total Amount',
    ord_items: 'Items',
    ord_no_history: 'No order history yet.',
    ord_shop_now: 'Start Shopping',
    ord_confirm_receipt: 'Confirm Receipt',
    ord_write_review: 'Review',
    ord_reviewed: 'Reviewed',
    ord_cancel_reason: 'Cancellation Reason',
    ord_not_specified: 'Not specified',
    ord_refund_info: 'Refund Information',
    ord_refund_pending: 'Admin is processing your refund.',
    ord_refund_no_info: 'Refund info not provided.',
    ord_provide_refund: 'Provide Refund Info',
    ord_refund_done: 'Refund processed successfully.',
    ord_refund_check_bank: 'Please check your bank account.',
    
    
    st_pending: 'Pending',
    st_shipped: 'Shipped',
    st_arrived: 'Arrived',
    st_delivered: 'Delivered',
    st_cancelled: 'Cancelled',
    st_refunded: 'Refunded',

    
    conf_receipt_title: 'Confirm Receipt?',
    conf_receipt_msg: 'Have you received and checked the product?',
    conf_receipt_btn: 'Confirm Received',
    
    
    rev_title: 'Write a Review',
    rev_rate: 'Rate this product',
    rev_placeholder: 'Share your experience with this product (Optional)',
    rev_submit: 'Submit Review',
    rev_submitting: 'Submitting...',
    rev_success: 'Thank you for your review!',

    
    ref_title: 'Refund Information',
    ref_desc: 'Please provide correct bank account details for the refund (Order #',
    ref_bank: 'Bank',
    ref_select_bank: '-- Select Bank --',
    ref_acc_name: 'Account Name',
    ref_acc_name_ph: 'Full name on account',
    ref_acc_num: 'Account Number / PromptPay',
    ref_acc_num_ph: 'Provide correct account number',
    ref_submitting: 'Saving...',
    ref_submit: 'Save Information',
    ref_success: 'Refund information saved. Admin will process it soon.',

    
    pay_title: 'Payment',
    pay_billing: 'Billing Information',
    pay_shipping_method: 'Shipping Method',
    pay_payment_method: 'Payment Method',
    pay_place_order: 'Place Order',
    pay_success: 'Order placed successfully!',
    pay_failed: 'Order failed',
    pay_back_cart: 'Back to Cart',
    pay_method_title: 'Payment Method',
    pay_bank_transfer: 'Bank Transfer',
    pay_bank_scb: 'Siam Commercial Bank (SCB)',
    pay_bank_kbank: 'Kasikorn Bank (K-Bank)',
    pay_bank_bbl: 'Bangkok Bank (BBL)',
    pay_bank_ktb: 'Krungthai Bank (KTB)',
    pay_bank_bay: 'Bank of Ayudhya (Krungsri)',
    pay_bank_ttb: 'TMBThanachart (ttb)',
    pay_acc_company: 'VELIN Co., Ltd.',
    pay_qr_code: 'PromptPay / QR Code',
    pay_qr_desc: 'Scan to pay',
    pay_qr_hint: 'Scan the QR code below to pay via PromptPay',
    pay_attach_slip: 'Attach slip here',
    pay_upload_slip: 'Upload Transfer Evidence',
    pay_change_slip: 'Change Image',
    pay_view_slip: 'View Refund Slip',
    pay_confirm: 'Confirm Payment',
    pay_bkk_only: 'Bangkok Only',
    pay_shipping_via: 'Shipping via',
    pay_credit_card: 'Credit / Debit Card',
    pay_summary: 'Order Summary',
    pay_missing_address: 'Please provide shipping address first',
    pay_missing_slip: 'Please attach payment slip',
    pay_select_shipping: 'Please select shipping method',
    order_success_title: 'Thank You for Your Order!',
    order_success_desc: 'Your payment has been successfully processed.',
    order_id: 'Order ID',
    order_success_check_history: 'You can check your order details in the Order History page.',
    back_home: 'Back to Home',

    
    prof_title: 'Account Settings',
    prof_account_info: 'Account Information',
    prof_personal: 'Personal Information',
    prof_shipping_addr: 'Shipping Address',
    
    
    prof_name: 'Full Name',
    prof_email: 'Email Address',
    prof_phone: 'Phone Number',
    prof_address: 'Shipping Address',
    prof_no_email: 'No email provided',
    prof_no_address: 'Please provide shipping address',
    
    
    prof_update: 'Update Profile',
    prof_success: 'Profile updated successfully!',
    prof_edit_address: 'Edit',
    prof_add_address: 'Add Shipping Address',
    prof_delete_address: 'Delete Address',
    prof_confirm_delete_address: 'Are you sure you want to delete this address?',
    prof_edit_address_title: 'Edit Shipping Address',

    
    prof_change_pw: 'Change Password',
    prof_old_pw: 'Current Password',
    prof_new_pw: 'New Password',
    prof_confirm_pw: 'Confirm New Password',
    prof_confirm_change_pw: 'Confirm Password Change',
    prof_pw_mismatch: 'New password and confirmation do not match',
    prof_pw_success: 'Password changed successfully',

    
    prof_address_header: 'Address',
    prof_full_name: 'Full Name',
    prof_address_detail: 'Address Details',
    prof_address_placeholder: 'House no., Street...',
    prof_addr_detail: 'Address Detail',
    prof_addr_ph: 'House no., Street, Mooban...',
    prof_sub_district: 'Sub-district',
    prof_prov_dist_zip: 'Province / District / Postal Code',
    prof_district: 'District',
    prof_province: 'Province',
    prof_postal_code: 'Postal Code',
    prof_location_label: 'District & Province',
    prof_map_location: 'Map Location',
    prof_map_expand_hint: 'Click to expand and select map location',
    prof_map_expand: 'Expand Map',
    prof_map_title: 'Shipping Map',
    prof_coords: 'Coords',
    prof_map_confirm: 'Confirm this location',
    prof_map_pos: 'Map Position',
    prof_confirm_pos: 'Confirm selection',
    prof_set_default: 'Set as default address',
    prof_address_success: 'Shipping address updated successfully',

    
    f_most_popular: 'Most Popular',
    f_nike: 'NIKE',
    f_apparel: 'APPAREL',
    f_popular_brands: 'Popular Brands',
    f_follow_us: 'Follow Us',
    f_about: 'About VELIN',
    f_our_story: 'Our Story',
    f_authenticity: 'Authenticity Guaranteed',
    f_store_locator: 'Store Locations',
    f_careers: 'Careers',
    f_support: 'Customer Support',
    f_contact: 'Contact Us',
    f_help: 'Help Center',
    f_faq: 'FAQ',
    f_shipping_info: 'Shipping Information',
    f_copyright: '2026 Copyright | VELIN',
    f_terms: 'Terms',
    f_privacy: 'Privacy',
    f_tagline: 'The Premier Destination for Curation & Rare Finds.',
    
    
    ship_title: 'Shipping & Delivery',
    ship_messenger_title: 'Messenger Delivery (Bangkok Only)',
    ship_messenger_desc: 'Fast delivery via courier after product verification. Same-day delivery available for ready-to-ship orders confirmed before 04:00 PM. (Fee calculated by distance)',
    ship_ems_title: 'EMS Express',
    ship_ems_desc: 'Standard delivery via logistics partners after verification (1-2 business days for ready-to-ship, 3-5 days for standard orders).',

    
    adm_dashboard: 'Dashboard',
    adm_products: 'Products',
    adm_orders: 'Orders',
    adm_delivered_orders: 'Orders Completed',
    adm_pending_orders: 'Pending / New Orders',
    adm_shipped_orders: 'Shipped / Remaining',
    adm_revenue: 'Revenue',
    adm_total_orders: 'Total Orders History',
    adm_bestsellers: 'Best Sellers',
    adm_logs: 'Activity Logs',
    adm_personnel: 'Personnel System',
    adm_manage: 'Manage Admins',
    adm_sales_dash: 'Sales Dashboard',
    adm_inventory_summary: 'Inventory Summary',
    adm_sales_by_brand: 'Sales by Brand',
    adm_top_brand: 'Top Performing Brand',
    adm_no_brand_data: 'No brand data available.',
    
    
    inv_title: 'Product Inventory & Summary',
    inv_th_product: 'Product',
    inv_th_sold: 'Sold Revenue (฿)',
    inv_th_sold_qty: 'Sold (Qty)',
    inv_th_remain: 'Stock Value (฿)',
    inv_th_remain_qty: 'Remaining (Qty)',
    inv_th_total_qty: 'Total Quantity',
    inv_th_total_val: 'Grand Total (Stock + Sales)',
    inv_th_price: 'Price',
    inv_th_item: 'Item',
    inv_th_size: 'Size',
    inv_th_quantity: 'Qty',
    inv_th_total: 'Total',

    
    adm_order_shipped: 'Order marked as shipped',
    adm_order_arrived: 'Order arrived at destination',
    adm_order_cancelled: 'Order cancelled successfully',
    adm_order_refunded: 'Order marked as Refunded',
    adm_order_fetch_failed: 'Failed to fetch order details',
    adm_order_update_failed: 'Failed to update order',
    adm_slip_verified: 'Slip verified',
    adm_slip_unverified: 'Slip unverified',
    adm_slip_update_failed: 'Failed to update slip status',
    adm_all_brands: 'All Brands',
    adm_no_revenue_data: 'No revenue data found for this selection.',
    adm_monthly_total: 'MONTHLY TOTAL',
    adm_no_sales_data_period: 'No sales data found for the selected period.',
    adm_last_sold: 'Last Sold',
    adm_monthly_desc: 'Breakdown of sales and units sold for each day in a month',
    adm_pay_verify: 'Payment Verification',
    adm_ship_status: 'Shipping Status',
    adm_no_orders: 'No orders found matching your filters.',
    adm_order_details: 'Order Details',
    adm_cust_info: 'Customer & Shipping Info',
    adm_items: 'Items',
    adm_total_pay: 'Total Pay',
    adm_curr_status: 'Current Status',
    adm_reason: 'Reason',
    adm_reason_label: 'Reason for cancellation',
    adm_wait_confirm: 'Waiting for customer to confirm receipt',
    adm_finalized: 'Finalized',
    adm_refund_success: 'Refund successful',
    adm_pending: 'Pending',
    adm_shipped: 'Shipped',
    adm_arrived: 'Arrived',
    adm_completed: 'Completed',
    adm_cancelled: 'Cancelled',
    adm_refunded: 'Refunded',
    adm_map_expand: 'Expand Map',
    adm_confirm_ship: 'Confirm Shipping',
    adm_confirm_ship_msg: 'Do you want to change status to "Shipped"?',
    adm_confirm_arrived: 'Confirm Arrival',
    adm_confirm_arrived_msg: 'Do you want to notify that products have arrived at destination?',
    adm_cancel_order: 'Cancel Order',
    adm_cancel_reason_ph: 'e.g. Out of stock, Incorrect info...',
    adm_cancel_notice: 'Notification will be sent to customer',
    adm_confirm_refund: 'Confirm Refund',
    adm_confirm_refund_msg: 'Have you already transferred the refund?',
    adm_no_coords: 'Coordinates not found (Customer not pinned)',
    adm_coords: 'Coords',
    adm_slip_view_hint: 'Click to view slip',
    adm_verified_hint: 'Verified',
    adm_pending_hint: 'Pending Check',
    adm_no_slip: 'No Slip',
    adm_map_pos_label: 'Map Location',
    adm_not_specified: 'Not specified',
    adm_refund_info: 'Refund Information',
    h_bank: 'Bank',
    h_acc_name: 'Account Name',
    h_acc_num: 'Account Number',

    
    view_detail: 'View Detail',
    nav_wishlist: 'Wishlist',
    nav_under: 'Under',
    nav_up: 'Up',
    nav_user_acc: 'User Account',

    
    auth_welcome: 'Welcome Back',
    auth_sign_in_desc: 'Sign in to your account',
    auth_create_acc: 'Create Account',
    auth_join_desc: 'Join Velin Inventory System',
    auth_username: 'Username',
    auth_password: 'Password',
    auth_confirm_password: 'Confirm Password',
    auth_email: 'Email',
    auth_register_now: 'Register now',
    auth_already_acc: 'Already have an account?',
    auth_sign_in: 'Sign In',
    auth_register: 'Register',
    auth_back_home: 'Back to Website',
    auth_dont_have_acc: "Don't have an account?",
    auth_login_success: 'Welcome back',
    auth_reg_success: 'Registration successful! Please login.',
    auth_pass_mismatch: 'Passwords do not match',
    auth_conn_error: 'Connection error',
    auth_login_failed: 'Login failed',
    auth_reg_failed: 'Registration failed',

    
    en: 'English',
    th: 'Thai',
    in: 'in',
    cm: 'cm',
    '2d': '2D',
    brand: 'Brand',
    type: 'Type',
    category: 'Category',
    sort: 'Sort',
    sale: 'Sale',
    cart_shipping_pending: 'TBD (Enter address)',
    week: 'Week',
    month: 'Month',

    
    super_admin_welcome: 'Welcome!',
    super_admin_desc_1: 'You are logged in as',
    super_admin_desc_2: 'Please select the system you want to access:',
    super_admin_btn_products: 'Manage Products / Orders (Normal)',
    super_admin_btn_admins: 'Manage Admins (Face Scan Required)',

    
    
    
    adm_role_super: 'SUPER ADMIN',

    
    adm_loading_best_sellers: 'Loading Best Sellers...',
    adm_top_products_showcase: 'Top Products Showcase',
    adm_print_hub_report: 'Print Hub Report',
    adm_units_sold: 'units sold',
    adm_units: 'units',
    adm_revenue_label: 'Revenue:',
    adm_top_performance: 'Top Performance',
    adm_full_catalog_performance: 'Full Catalog Performance (Ranked by Sales Volume)',
    adm_no_sales_data: 'No sales data recorded yet.',
    adm_rank: 'Rank',
    adm_product_id: 'Product ID',
    adm_product_details: 'Product Details',
    adm_category: 'Category',
    adm_sales_volume: 'Sales Volume',
    adm_revenue_gross: 'Revenue (Gross)',
    adm_status: 'Status',
    adm_sold: 'SOLD',
    adm_status_peak: 'Peak',
    adm_status_top_tier: 'Top Tier',
    adm_status_stable: 'Stable',
    adm_prev: 'Prev',
    adm_next: 'Next',

    
    adm_overview: 'Overview',
    adm_forecast_7_days: 'Forecast (Last 7 Days)',
    adm_trend_year: 'Trend for Year',
    adm_low_stock_alerts: 'Low Stock Alerts',
    adm_by_size: 'By Size',
    adm_by_total: 'By Total',
    adm_all_stock_sufficient: 'All stock levels sufficient.',
    adm_sold_lower: 'sold',
    adm_daily_performance: 'Daily Performance',
    adm_revenue_target: 'Revenue Target:',
    adm_order_volume: 'Order Volume:',
    adm_lifetime_analytics: 'Lifetime Analytics',
    adm_gross_revenue: 'Gross Revenue:',
    adm_inventory_velocity: 'Inventory Velocity:',
    adm_items_sold: 'items sold',
    adm_lifetime_desc: 'Comprehensive data insight across all operational cycles. Growth rate and inventory turnover are benchmarked against historical performance.',

    
    adm_manage_orders: 'Manage Customer Orders',
    adm_status_pending: 'Pending',
    adm_status_shipped: 'Shipped',
    adm_status_arrived: 'Arrived',
    adm_status_delivered: 'Completed',
    adm_status_cancelled: 'Cancelled',
    adm_status_refunded: 'Refunded',
    adm_payment_verification: 'Payment Verification',
    adm_shipping_status: 'Shipping Status',
    adm_order_id: 'Order ID',
    adm_customer: 'Customer',
    adm_date: 'Date',
    adm_total: 'Total',
    adm_slip_check: 'Slip Check',
    adm_actions: 'Actions',
    adm_no_orders_found: 'No orders found matching your filters.',

    
    adm_manage_products: 'Manage Products',
    adm_filter: 'Filter',
    adm_total_low: 'Stock < 5',
    adm_table_image: 'IMAGE',
    adm_table_code: 'CODE',
    adm_table_name: 'NAME',
    adm_table_category: 'CATEGORY',
    adm_table_brand: 'BRAND',
    adm_table_price: 'PRICE',
    adm_table_discount: 'DISCOUNT',
    adm_table_final_price: 'FINAL PRICE',
    adm_table_sizes: 'SIZES',
    adm_table_stock: 'STOCK',
    adm_table_actions: 'ACTIONS',
    adm_export_pdf: 'Export PDF',
    adm_financial_summary: 'Financial Summary (฿)',
    adm_all_orders: 'All Orders',
    adm_pending_check: 'Pending Check',
    adm_verified_only: 'Verified Only',
    adm_all_status: 'All Status',
    adm_bank_notified: 'Bank Notified',
    adm_edit_product: 'Edit Product',
    adm_add_color: 'Add Product Color',
    adm_form_name: 'Name',
    adm_form_code: 'Product Code',
    adm_form_price: 'Price (฿)',
    adm_form_discount: 'Discount (%)',
    adm_form_category: 'Category',
    adm_form_brand: 'Brand',
    adm_form_desc: 'Description',
    adm_form_gallery: 'Manage Gallery',
    adm_form_cover: 'Cover',
    adm_form_stock: 'Stock',
    adm_form_size_guide: 'Size Guide',
    adm_form_chest_label: 'Chest',
    adm_form_length_label: 'Length',
    adm_form_add_stock: '+ Add Stock',
    adm_form_add_guide: '+ Add Guide Entry',
    adm_form_save: 'Save Changes',
    adm_form_cancel: 'Cancel',
    adm_form_add_photos: '+ Add Photos',
    adm_print_report: 'Print PDF Report',
    adm_revenue_hub: 'Revenue Performance Hub',
    adm_todays_revenue: "Today's Revenue",
    adm_this_month: 'This Month',
    adm_lifetime_revenue: 'Lifetime Revenue',
    adm_vs_yesterday: 'vs yesterday',
    adm_vs_last_month: 'vs last month',
    adm_peak_hours: 'Peak Hours',
    adm_revenue_stats: 'Revenue Statistics Analysis',
    adm_daily_revenue_history: 'Daily Revenue History',
    adm_revenue_strategy: 'Revenue Strategy Summary',
    adm_total_sales_revenue: 'Total Sales Revenue',
    adm_total_items_sold: 'Total Items Sold',
    adm_revenue_breakdown: 'Detailed Revenue Breakdown',
    adm_monthly_performance_log: 'Monthly Daily Performance Log',
    adm_revenue_contribution: 'Revenue contribution',
    adm_units_sold_items: 'Units Sold',
    adm_daily_sales_cal: 'Daily Sales Calendar',
    adm_revenue_summary_desc: 'This summary represents the accumulated performance across all business cycles. Use the chart above to identify growth trends and peak performance months.',
    adm_page_label: 'Page:',
    adm_page: 'Page',
    adm_of: 'of',
    adm_logs_loading: 'Loading Logs...',
    adm_logs_title: 'System Activity Logs',
    adm_logs_desc: 'Track and monitor all admin activities, inventory updates, and order changes.',
    adm_logs_th_datetime: 'Date/Time',
    adm_logs_th_admin: 'Admin',
    adm_logs_th_action: 'Action',
    adm_logs_th_target: 'Target',
    adm_logs_th_entity: 'Entity ID',
    adm_logs_th_details: 'Details',
    adm_logs_no_activity: 'No activity logs found.',
    adm_loading_product_details: 'Loading Product Details...',
    adm_variants_colors: 'Variants / Colors',
    adm_available_sizes: 'Available Sizes',
    adm_product_details_section: 'Product Details',
    adm_no_description: 'No description available for this product.',
    adm_size_guide_title: 'Size Guide',
    adm_customer_reviews: 'Customer Reviews',
    adm_no_reviews: 'No reviews for this product yet.',
    adm_edit_product_details: 'Edit Product Details',
    adm_product_name: 'Product Name',
    adm_manage_gallery_desc: 'Manage Gallery (First image is cover, use ◀ ▶ to reorder)',
    adm_add_photos: 'Add Photos',
    adm_code_label: 'Code:',
    adm_category_label: 'Category:',
    adm_in_stock: 'In Stock',
    adm_out_of_stock: 'Out of Stock',
    adm_units_left: 'left',
    adm_all_sizes: 'All Sizes',
    adm_size_low: 'Size < 5',
    adm_search_products: 'Search products...',
    adm_add_product: '+ Add Product',
    adm_ship: 'Ship',
    adm_arrive: 'Arrive',
    adm_workforce_mgmt: 'Workforce Management',
    adm_workforce_desc: 'Personnel security and role assignment',
    adm_total_personnel: 'Total Personnel',
    adm_super_admins: 'Super Admins',
    adm_biometrics_registered: 'Biometrics Registered',
    adm_personnel_access_list: 'Personnel Access List',
    adm_personnel_access_desc: 'All registered administrators and their security levels',
    adm_add_new_admin: 'Add New Admin',
    adm_role_admin: 'Standard Admin',
    adm_role_superadmin: 'Super Admin',
    adm_no_email_provided: 'No email provided',
    adm_table_personnel: 'Personnel',
    adm_table_permissions: 'Permissions',
    adm_table_biometrics: 'Biometrics',
    adm_table_management: 'Management',
    adm_biometrics_required: 'REQUIRED',
    adm_biometrics_registered_badge: 'REGISTERED',
    adm_biometrics_standard: 'STANDARD',
    adm_initiate_scan: 'Initiate Biometric Scan',
    adm_active_biometric_login: 'ACTIVE BIOMETRIC LOGIN',
    adm_update_rescan: 'Update / Re-scan Face Data',
    adm_create_access_token: 'Create Access Token',
    adm_update_credentials: 'Update Credentials',
    adm_superadmin_face_required: 'Biometric face data required for Super Admin.',
    adm_security_req: 'Security Requirement',
    adm_reset_face_error: 'Error resetting face data.',
    adm_reset_biometrics: 'Reset Biometrics',
    adm_reset_face_data: 'Reset Face Data',
    adm_scan_face_now: 'Scan Face Now',
    edit: 'Edit',
    delete: 'Delete',
    adm_admin_updated: 'Admin updated successfully.',
    adm_admin_added: 'New admin added successfully.',
    adm_confirm_delete: 'Confirm Deletion',
    adm_delete_admin_confirm: 'Are you sure you want to delete this admin? This action cannot be undone.',
    adm_reset_face_confirm: 'Are you sure you want to reset face data for {{username}}?',
    adm_reset_success: 'Face data reset successfully.',
    adm_form_password: 'Access Password',
  },
  th: {
    
    ok: 'ตกลง',
    dismiss: 'รับทราบ',
    login: 'เข้าสู่ระบบ',
    register: 'สมัครสมาชิก',
    cancel: 'ยกเลิก',
    confirm: 'ยืนยัน',
    save: 'บันทึกการเปลี่ยนแปลง',
    back: 'กลับ',
    next: 'ถัดไป',
    previous: 'ก่อนหน้า',
    loading: 'กำลังโหลด...',
    total: 'ทั้งหมด',
    quantity: 'จำนวน',
    size: 'ไซส์',
    remove: 'ลบออก',
    success: 'สำเร็จ',
    error: 'เกิดข้อผิดพลาด',
    username: 'ชื่อผู้ใช้',
    email: 'อีเมล',
    full_name: 'ชื่อ-นามสกุล',
    phone: 'เบอร์โทรศัพท์',
    postal_code: 'รหัสไปรษณีย์',

    
    auth_title_order: 'เข้าสู่ระบบเพื่อสั่งซื้อ',
    auth_msg_order: 'กรุณาเข้าสู่ระบบหรือสมัครสมาชิกก่อนสั่งซื้อสินค้านะครับ',
    auth_title_wish: 'รายการโปรด',
    auth_msg_wish: 'กรุณาเข้าสู่ระบบหรือสมัครสมาชิกเพื่อบันทึกรายการโปรดนะครับ',
    auth_title_comment: 'แสดงความคิดเห็น',
    auth_msg_comment: 'กรุณาเข้าสู่ระบบเพื่อแสดงความคิดเห็นนะครับ',

    
    nav_home: 'หน้าหลัก',
    nav_products: 'สินค้า',
    nav_categories: 'หมวดหมู่',
    nav_price: 'ราคา',
    nav_brands: 'แบรนด์',
    nav_product_types: 'ประเภทสินค้า',
    nav_recommended: 'สินค้าแนะนำ',
    nav_newest: 'สินค้าใหม่ล่าสุด',
    nav_popular: 'ยอดนิยม',
    nav_promo: 'โปรโมชั่นพิเศษ',
    nav_min: 'ต่ำสุด',
    nav_max: 'สูงสุด',
    nav_search_price: 'ค้นหาตามราคา',
    nav_search_placeholder: 'ค้นหาสินค้า...',
    nav_no_found: 'ไม่พบสินค้า',
    nav_my_orders: 'ประวัติการสั่งซื้อ',
    nav_login_reg: 'เข้าสู่ระบบ / สมัครสมาชิก',
    nav_profile: 'บัญชี',
    nav_logout: 'ออกจากระบบ',
    nav_apparel: 'เสื้อผ้า',
    nav_shoes: 'รองเท้า',
    nav_under_5k: 'ต่ำกว่า 5,000',
    nav_above_50k: '50,000 ขึ้นไป',

    
    h_collection: 'คอลเลกชัน',
    h_exclusive: 'สินค้าพิเศษ',
    h_new_coll: 'คอลเลกชันใหม่ 2026',
    h_lookbook: 'THE LOOKBOOK 2026',
    h_lookbook_desc: 'คัดสรรสินค้าหายากและคอลเลกชันล่าสุด เพื่อนิยามสไตล์ใหม่ในแบบคุณ',
    h_buy_now: 'ซื้อตอนนี้',
    h_sold_out: 'สินค้าหมด',
    h_shop_drop: 'ดูสินค้าทั้งหมด',
    h_shop_now: 'ช้อปเลย',
    h_exclusive_drop: 'เปิดตัวสุดเอ็กซ์คลูซีฟ',
    h_cactus_jack: 'CACTUS JACK\nTRAVIS SCOTT',
    h_ts_desc: 'การเปิดตัว Air Jordan 1 Low OG WMNS "Olive" ที่รอคอยมาถึงแล้ว ยกระดับสไตล์ของคุณเลย',
    h_new_coll_2026: 'คอลเลกชันใหม่ 2026',
    h_adidas_title: 'ADIDAS ORIGINALS\nCTT JACKET',
    h_adidas_desc: 'สัมผัสคอลเลกชันล่าสุดของเรา ด้วยเนื้อผ้าพรีเมียมในโทนสีที่ทุกคนต้องมี',
    h_items_left: 'รายการสุดท้าย',
    h_loading_exp: 'กำลังโหลดประสบการณ์ Velin...',
    h_go_home: 'กลับหน้าหลัก',

    
    ps_found: 'พบสินค้า',
    ps_items: 'รายการ',
    ps_filter_by: 'กรองโดย',
    ps_no_products: 'ไม่พบสินค้าที่คุณต้องการในขณะนี้',
    ps_go_back: 'กลับไปหน้าขาย',
    ps_all_products: 'สินค้าทั้งหมด',
    ps_featured: 'สินค้าแนะนำ',
    ps_premium_coll: 'คอลเลกชันพรีเมียม',
    ps_desc_nike: 'Nike (ไนกี้) ก่อตั้งในปี 1964 โดย Bill Bowerman และ Phil Knight ในฐานะ \'Blue Ribbon Sports\' ก่อนจะเปลี่ยนชื่อเป็น Nike ในปี 1971 ด้วยสัญลักษณ์ Swoosh อันเป็นเอกลักษณ์และสโลแกน \'Just Do It\' ไนกี้ได้กลายเป็นผู้นำระดับโลกด้านรองเท้าและเครื่องแต่งกายกีฬาที่ผสมผสานนวัตกรรมและแฟชั่นเข้าด้วยกันอย่างลงตัว',
    ps_desc_adidas: 'Adidas (อาดิดาส) ยักษ์ใหญ่จากเยอรมัน ก่อตั้งโดย Adolf \'Adi\' Dassler ในปี 1949 ด้วยวิสัยทัศน์ที่ต้องการผลิตรองเท้ากีฬาที่ดีที่สุดสำหรับนักกีฬา ตลอดหลายทศวรรษที่ผ่านมา อาดิดาสได้สร้างตำนาน \'Three Stripes\' และกลายเป็นศูนย์กลางของวัฒนธรรมสตรีทแวร์และวงการกีฬาโลก',
    ps_desc_stussy: 'Stussy (สตุสซี่) แบรนด์ระดับตำนานที่นิยามคำว่า \'Streetwear\' อย่างแท้จริง เริ่มต้นขึ้นในช่วงต้นยุค 80 โดย Shawn Stussy ในย่าน Laguna Beach จากแบรนด์สำหรับชาวเซิร์ฟสู่ไอคอนระดับโลกที่ผสมผสานวัฒนธรรมฮิปฮอป พังก์ และสไตล์ไฮแฟชั่นเข้าด้วยกันอย่างลงตัว',
    ps_desc_new_balance: 'New Balance ก่อตั้งในปี 1906 โดยเริ่มต้นจากการผลิตอุปกรณ์พยุงอุ้งเท้า (Arch Supports) ในบอสตัน ก่อนจะก้าวขึ้นเป็นแบรนด์รองเท้าระดับโลกที่ขึ้นชื่อเรื่องความสบาย คุณภาพการผลิตที่พิถีพิถัน และดีไซน์แบบ \'Dad Shoes\' ที่กลายเป็นเทรนด์ยอดฮิตทั่วโลก',
    ps_desc_asics: 'Asics ก่อตั้งในปี 1949 โดย Kihachiro Onitsuka ภายใต้ชื่อ Onitsuka Tiger ด้วยความเชื่อที่ว่า \'จิตใจที่แจ่มใสอยู่ในร่างกายที่แข็งแรง\' (Anima Sana In Corpore Sano) เอสิกส์จึงมุ่งเน้นความเป็นเลิศทางวิศวกรรมเพื่อรองเท้าที่ช่วยปลดล็อกศักยภาพสูงสุดของนักกีฬา',
    ps_desc_converse: 'Converse (คอนเวิร์ส) ก่อตั้งขึ้นในปี 1908 และสร้างตำนานบทใหม่ในปี 1917 ด้วยรองเท้าบาสเกตบอล Chuck Taylor All-Star ด้วยดีไซน์คลาสสิกที่ก้าวข้ามกาลเวลา คอนเวิร์สจึงกลายเป็นสัญลักษณ์ของสตรีทแฟชั่น ดนตรีป๊อปพังก์ และการแสดงออกถึงตัวตนอย่างแท้จริง',
    ps_desc_puma: 'Puma ก่อตั้งโดย Rudolf Dassler ในปี 1948 ณ ประเทศเยอรมัน พูม่าสร้างชื่อเสียงระดับโลกผ่านนวัตกรรมที่รวดเร็วและความร่วมมือกับไอคอนระดับโลกมากมาย ผสมผสานไลฟ์สไตล์แบบสปอร์ตเข้ากับแฟชั่นยุคใหม่ได้อย่างลงตัว',
    ps_desc_default: 'VELIN คัดสรรผลิตภัณฑ์คุณภาพเยี่ยมจากแบรนด์ชั้นนำทั่วโลก เพื่อให้คุณได้สัมผัสกับสไตล์ที่โดดเด่นและนวัตกรรมล่าสุดในวงการแฟชั่นทุกประเภท ไม่ว่าจะเป็นรองเท้า เสื้อผ้า หรืออุปกรณ์เสริมที่สะท้อนความเป็นตัวคุณ',

    
    pd_available_sizes: 'ไซส์ที่พร้อมส่ง',
    pd_selected: 'เลือกแล้ว',
    pd_available_colors: 'สีอื่นๆ ที่มี',
    pd_quantity: 'จำนวน',
    pd_add_to_cart: 'เพิ่มลงตะกร้า',
    pd_select_size: 'เลือกไซส์',
    pd_details: 'รายละเอียดสินค้า',
    pd_reviews: 'รีวิวสินค้า',
    pd_all_reviews: 'รีวิวทั้งหมด',
    pd_no_desc: 'ยังไม่มีรายละเอียดสินค้า',
    pd_no_reviews: 'ยังไม่มีรีวิวสำหรับสินค้านี้',
    pd_write_review: 'เขียนรีวิว',
    pd_shipping_info: 'ข้อมูลการจัดส่ง',
    pd_auth_required: 'จำเป็นต้องเข้าสู่ระบบ',
    pd_auth_msg: 'กรุณาเข้าสู่ระบบเพื่อเพิ่มสินค้าลงตะกร้า',
    pd_back: 'กลับ',
    pd_in_stock: 'มีสินค้า',
    pd_code: 'รหัสสินค้า',
    pd_category: 'หมวดหมู่',
    pd_items_unit: 'ชิ้น',
    pd_not_found: 'ไม่พบสินค้า',
    pd_stock_limit: 'จำนวนสินค้าเกินสต็อกที่มีอยู่',
    pd_rate_error: 'กรุณาให้คะแนนดาวก่อนส่งรีวิว',
    pd_comment_success: 'ส่งความคิดเห็นเรียบร้อยแล้ว!',

    
    cart_title: 'ตะกร้าสินค้าของคุณ',
    cart_empty: 'ตะกร้าของคุณยังว่างอยู่',
    cart_go_shop: 'ไปเลือกซื้อสินค้า',
    cart_summary: 'สรุปยอดคำสั่งซื้อ',
    cart_subtotal: 'ยอดรวมสินค้า',
    cart_discount: 'ส่วนลดสินค้า',
    cart_shipping: 'ค่าจัดส่ง',
    cart_free: 'ฟรี',
    cart_total: 'ยอดสุทธิ',
    cart_checkout: 'ดำเนินการชำระเงิน',
    cart_added: 'เพิ่มลงตะกร้าแล้ว',
    cart_add_success: 'เพิ่มลงตะกร้าแล้ว!',
    cart_remove_success: 'เอาสินค้าออกจากตะกร้าแล้ว',

    
    wish_added: 'เพิ่มรายการโปรดแล้ว!',
    wish_removed: 'นำออกจากรายการโปรดแล้ว',
    wish_subtitle: 'สินค้าที่คุณสนใจและบันทึกไว้',
    wish_empty: 'ไม่มีรายการโปรด',
    wish_empty_desc: 'กลับไปเลือกชมสินค้าที่คุณถูกใจแล้วบันทึกไว้ที่นี่',

    
    ord_title: 'ประวัติการสั่งซื้อ',
    ord_number: 'คำสั่งซื้อ',
    ord_date: 'วันที่',
    ord_status: 'สถานะ',
    ord_total: 'ราคารวม',
    ord_items: 'รายการ',
    ord_no_history: 'ยังไม่มีประวัติการสั่งซื้อ',
    ord_shop_now: 'เลือกซื้อสินค้าเลย',
    ord_confirm_receipt: 'ยืนยันการรับสินค้า',
    ord_write_review: 'เขียนรีวิว',
    ord_reviewed: 'รีวิวแล้ว',
    ord_cancel_reason: 'เหตุผลที่ยกเลิก',
    ord_not_specified: 'ไม่ได้ระบุเหตุผล',
    ord_refund_info: 'ข้อมูลการคืนเงิน',
    ord_refund_pending: 'แอดมินกำลังดำเนินการคืนเงินให้ท่าน',
    ord_refund_no_info: 'ยังไม่ได้แจ้งข้อมูลคืนเงิน',
    ord_provide_refund: 'แจ้งข้อมูลคืนเงิน',
    ord_refund_done: 'คืนเงินเรียบร้อยแล้ว',
    ord_refund_check_bank: 'กรุณาตรวจสอบยอดเงินในบัญชี',
    
    
    st_pending: 'รอดำเนินการ',
    st_shipped: 'จัดส่งแล้ว',
    st_arrived: 'ถึงที่หมาย',
    st_delivered: 'สำเร็จแล้ว',
    st_cancelled: 'ยกเลิก',
    st_refunded: 'คืนเงินแล้ว',

    
    conf_receipt_title: 'ยืนยันได้รับสินค้า?',
    conf_receipt_msg: 'คุณตรวจสอบและได้รับสินค้าเรียบร้อยแล้วใช่หรือไม่?',
    conf_receipt_btn: 'ยืนยันรับของ',
    
    
    rev_title: 'เขียนรีวิวสินค้า',
    rev_rate: 'ให้คะแนนสินค้านี้',
    rev_placeholder: 'แชร์ประสบการณ์ของคุณเกี่ยวกับสินค้านี้ (ไม่บังคับ)',
    rev_submit: 'ส่งรีวิว',
    rev_submitting: 'กำลังส่ง...',
    rev_success: 'ขอบคุณสำหรับรีวิวของคุณ!',

    
    ref_title: 'แจ้งข้อมูลเพื่อรับเงินคืน',
    ref_desc: 'กรุณากรอกข้อมูลบัญชีธนาคารเพื่อให้เราโอนเงินคืน (ออเดอร์ #',
    ref_bank: 'ธนาคาร',
    ref_select_bank: '-- เลือกธนาคาร --',
    ref_acc_name: 'ชื่อบัญชี',
    ref_acc_name_ph: 'ชื่อ-นามสกุลเจ้าของบัญชี',
    ref_acc_num: 'เลขบัญชี / เบอร์พร้อมเพย์',
    ref_acc_num_ph: 'ระบุเลขบัญชีที่ถูกต้อง',
    ref_submitting: 'กำลังบันทึก...',
    ref_submit: 'บันทึกข้อมูล',
    ref_success: 'บันทึกข้อมูลคืนเงินเรียบร้อยแล้ว',

    
    pay_title: 'ชำระเงิน',
    pay_billing: 'ข้อมูลที่อยู่จัดส่ง',
    pay_shipping_method: 'วิธีการจัดส่ง',
    pay_payment_method: 'วิธีการชำระเงิน',
    pay_place_order: 'ยืนยันการสั่งซื้อ',
    pay_success: 'สั่งซื้อสินค้าสำเร็จ!',
    pay_failed: 'การสั่งซื้อล้มเหลว',
    pay_back_cart: 'กลับไปตะกร้า',
    pay_method_title: 'วิธีการชำระเงิน',
    pay_bank_transfer: 'โอนเงินผ่านธนาคาร',
    pay_bank_scb: 'ธนาคารไทยพาณิชย์ (SCB)',
    pay_bank_kbank: 'ธนาคารกสิกรไทย (K-Bank)',
    pay_bank_bbl: 'ธนาคารกรุงเทพ (BBL)',
    pay_bank_ktb: 'ธนาคารกรุงไทย (KTB)',
    pay_bank_bay: 'ธนาคารกรุงศรีอยุธยา (Krungsri)',
    pay_bank_ttb: 'ทหารไทยธนชาต (ttb)',
    pay_acc_company: 'บริษัท เวลิน จำกัด (VELIN Co., Ltd.)',
    pay_qr_code: 'พร้อมเพย์ / QR Code',
    pay_qr_desc: 'สแกนเพื่อชำระเงิน',
    pay_qr_hint: 'สแกน QR Code ด้านล่างเพื่อชำระเงินผ่าน PromptPay',
    pay_attach_slip: 'แนบสลิปที่นี่',
    pay_upload_slip: 'อัพโหลดหลักฐานการโอน',
    pay_change_slip: 'เปลี่ยนรูปภาพ',
    pay_view_slip: 'ดูหลักฐานการคืนเงิน',
    pay_confirm: 'ยืนยันการชำระเงิน',
    pay_bkk_only: 'เฉพาะกรุงเทพฯ',
    pay_shipping_via: 'การจัดส่งผ่าน',
    pay_credit_card: 'บัตรเครดิต/เดบิต',
    order_success_title: 'ขอบคุณสำหรับการสั่งซื้อ!',
    order_success_desc: 'การชำระเงินของคุณได้รับการดำเนินการสำเร็จแล้ว',
    order_id: 'หมายเลขคำสั่งซื้อ',
    order_success_check_history: 'คุณสามารถตรวจสอบรายละเอียดคำสั่งซื้อของคุณได้ที่หน้าประวัติการสั่งซื้อ',
    back_home: 'กลับหน้าหลัก',

    
    prof_title: 'การตั้งค่าบัญชี',
    prof_account_info: 'ข้อมูลบัญชี',
    prof_personal: 'ข้อมูลส่วนตัว',
    prof_shipping_addr: 'ที่อยู่จัดส่ง',
    
    
    prof_name: 'ชื่อ-นามสกุล',
    prof_email: 'อีเมล',
    prof_phone: 'เบอร์โทรศัพท์',
    prof_address: 'ที่อยู่สำหรับจัดส่ง',
    prof_no_email: 'ไม่ได้ระบุอีเมล',
    prof_no_address: 'กรุณาระบุที่อยู่จัดส่ง',
    
    
    prof_update: 'อัปเดตข้อมูล',
    prof_success: 'อัปเดตข้อมูลโปรไฟล์แล้ว!',
    prof_edit_address: 'แก้ไข',
    prof_add_address: 'เพิ่มที่อยู่จัดส่ง',
    prof_delete_address: 'ลบที่อยู่จัดส่ง',
    prof_confirm_delete_address: 'คุณแน่ใจหรือไม่ที่จะลบที่อยู่จัดส่งนี้?',
    prof_edit_address_title: 'แก้ไขที่อยู่จัดส่ง',

    
    prof_change_pw: 'เปลี่ยนรหัสผ่าน',
    prof_old_pw: 'รหัสผ่านปัจจุบัน',
    prof_new_pw: 'รหัสผ่านใหม่',
    prof_confirm_pw: 'ยืนยันรหัสผ่านใหม่',
    prof_confirm_change_pw: 'ยืนยันการเปลี่ยนรหัสผ่าน',
    prof_pw_mismatch: 'รหัสผ่านใหม่และการยืนยันไม่ตรงกัน',
    prof_pw_success: 'เปลี่ยนรหัสผ่านเรียบร้อยแล้ว',

    
    prof_address_header: 'ที่อยู่',
    prof_full_name: 'ชื่อ นามสกุล',
    prof_address_detail: 'รายละเอียดที่อยู่',
    prof_address_placeholder: 'บ้านเลขที่, ถนน...',
    prof_addr_detail: 'รายละเอียดที่อยู่',
    prof_addr_ph: 'บ้านเลขที่, ถนน, หมู่บ้าน...',
    prof_sub_district: 'แขวง / ตำบล',
    prof_prov_dist_zip: 'จังหวัด / เขต / รหัสไปรษณีย์',
    prof_district: 'เขต / อำเภอ',
    prof_province: 'จังหวัด',
    prof_postal_code: 'รหัสไปรษณีย์',
    prof_location_label: 'เขตและจังหวัด',
    prof_map_location: 'ตำแหน่งบนแผนที่',
    prof_map_expand_hint: 'คลิกเพื่อขยายและเลือกตำแหน่งแผนที่',
    prof_map_expand: 'ขยายแผนที่',
    prof_map_title: 'แผนที่จัดส่ง',
    prof_coords: 'พิกัด',
    prof_map_confirm: 'ยืนยันตำแหน่งนี้',
    prof_map_pos: 'ตำแหน่งบนแผนที่',
    prof_confirm_pos: 'ยืนยันตำแหน่งนี้',
    prof_set_default: 'ตั้งเป็นที่อยู่หลัก',
    prof_address_success: 'อัปเดตที่อยู่จัดส่งเรียบร้อย',

    
    f_most_popular: 'สินค้าขายดี',
    f_nike: 'NIKE',
    f_apparel: 'เครื่องแต่งกาย',
    f_popular_brands: 'แบรนด์ยอดนิยม',
    f_follow_us: 'ติดตามเรา',
    f_about: 'เกี่ยวกับ VELIN',
    f_our_story: 'เรื่องราวของเรา',
    f_authenticity: 'รับประกันของแท้',
    f_store_locator: 'ที่ตั้งสาขา',
    f_careers: 'ร่วมงานกับเรา',
    f_support: 'ช่วยเหลือลูกค้า',
    f_contact: 'ติดต่อเรา',
    f_help: 'ศูนย์ช่วยเหลือ',
    f_faq: 'คำถามที่พบบ่อย',
    f_shipping_info: 'ข้อมูลการจัดส่ง',
    f_copyright: '2026 ลิขสิทธิ์ | VELIN',
    f_terms: 'ข้อกำหนด',
    f_privacy: 'ความเป็นส่วนตัว',

    
    ship_title: 'การจัดส่งและขนส่ง',
    ship_messenger_title: 'จัดส่งเมสเซนเจอร์ (เฉพาะกรุงเทพฯ)',
    ship_messenger_desc: 'จัดส่งด่วนหลังการตรวจสอบสินค้า เลือกส่งในวันเดียวกันได้สำหรับคำสั่งซื้อพร้อมส่งที่ยืนยันก่อน 16:00 น. (ราคาตามระยะทาง)',
    ship_ems_title: 'ส่งแบบ EMS ด่วน',
    ship_ems_desc: 'จัดส่งโดยพาร์ทเนอร์หลังผ่านการตรวจสอบ (1-2 วันทำการสำหรับสินค้าพร้อมส่ง, 3-5 วันสำหรับเคสปกติ)',

    
    adm_dashboard: 'แดชบอร์ด',
    adm_products: 'จัดการสินค้า',
    adm_orders: 'ออเดอร์',
    adm_delivered_orders: 'ออเดอร์ที่สำเร็จแล้ว',
    adm_pending_orders: 'ออเดอร์เข้ามาใหม่/รอดำเนินการ',
    adm_shipped_orders: 'ออเดอร์ที่จัดส่งแล้ว/ตกค้าง',
    adm_revenue: 'รายได้',
    adm_total_orders: 'ออเดอร์ทั้งหมดในระบบ',
    adm_bestsellers: 'สินค้าขายดี',
    adm_logs: 'ประวัติการใช้งาน',
    adm_manage: 'จัดการแอดมิน',
    adm_sales_dash: 'หน้าขายสินค้า',
    adm_inventory_summary: 'สรุปคลังสินค้า',
    adm_sales_by_brand: 'ยอดขายตามแบรนด์',
    adm_top_brand: 'แบรนด์ที่ทำยอดขายได้สูงสุด',
    adm_no_brand_data: 'ไม่มีข้อมูลแบรนด์',
    
    
    inv_title: 'สรุปผลิตภัณฑ์และคลังสินค้า',
    inv_th_product: 'สินค้า',
    inv_th_sold: 'ยอดขายสุทธิ (สำเร็จแล้ว)',
    inv_th_sold_qty: 'ขายแล้ว (ชิ้น)',
    inv_th_remain: 'มูลค่าสต็อก',
    inv_th_remain_qty: 'คงเหลือ',
    inv_th_total_qty: 'จำนวนรวม',
    inv_th_total_val: 'มูลค่าสินค้ารวมทั้งหมด',
    inv_th_price: 'ราคา',
    inv_th_item: 'สินค้า',
    inv_th_size: 'ไซส์',
    inv_th_quantity: 'จำนวน',
    inv_th_total: 'ยอดรวม',
    inv_th_price_per_unit: 'ราคา/ชิ้น',

    
    adm_order_shipped: 'แจ้งจัดส่งสินค้าเรียบร้อยแล้ว',
    adm_order_arrived: 'แจ้งสินค้าถึงที่หมายเรียบร้อยแล้ว',
    adm_order_cancelled: 'ยกเลิกคำสั่งซื้อเรียบร้อยแล้ว',
    adm_order_refunded: 'คืนเงินเรียบร้อยแล้ว',
    adm_order_fetch_failed: 'ไม่สามารถดึงข้อมูลคำสั่งซื้อได้',
    adm_order_update_failed: 'ไม่สามารถอัปเดตสถานะออเดอร์ได้',
    adm_slip_verified: 'ตรวจสอบสลิปเรียบร้อยแล้ว',
    adm_slip_unverified: 'ยกเลิกการตรวจสอบสลิป',
    adm_slip_update_failed: 'ไม่สามารถอัปเดตสถานะสลิปได้',
    adm_all_brands: 'ทุกแบรนด์',
    adm_no_revenue_data: 'ไม่พบข้อมูลรายได้จากการเลือกนี้',
    adm_monthly_total: 'ยอดรวมทั้งเดือน',
    adm_no_sales_data_period: 'ไม่พบข้อมูลการขายในช่วงเวลาที่เลือก',
    adm_revenue_hub: 'ศูนย์สรุปข้อมูลรายได้',
    adm_todays_revenue: 'รายได้วันนี้',
    adm_vs_yesterday: 'เปรียบเทียบกับเมื่อวาน',
    adm_this_month: 'เดือนนี้',
    adm_vs_last_month: 'เปรียบเทียบกับเดือนที่แล้ว',
    adm_lifetime_revenue: 'รายได้ตลอดการเปิดร้าน',
    adm_daily_sales_cal: 'ปฏิทินยอดขายรายวัน',
    adm_peak_hours: 'ช่วงเวลาที่มีการซื้อสูงสุด',
    adm_revenue_stats: 'การวิเคราะห์สถิติรายได้',
    adm_daily_revenue_history: 'บันทึกรายได้รายวัน',
    adm_revenue_strategy: 'สรุปกลยุทธ์รายได้',
    adm_total_sales_revenue: 'รายได้จากการขายรวม',
    adm_total_items_sold: 'จำนวนสินค้าที่ขายได้รวม',
    adm_revenue_summary_desc: 'ข้อมูลสรุปนี้แสดงถึงผลการดำเนินงานสะสมในทุกรอบธุรกิจ ใช้แผนภูมิด้านบนเพื่อระบุแนวโน้มการเติบโตและเดือนที่มีผลงานสูงสุด ร้านค้าของคุณกำลังแสดงรูปแบบการเติบโตที่มั่นคง',
    adm_revenue_breakdown: 'รายละเอียดการแยกประเภทรายได้',
    adm_last_sold: 'ขายล่าสุดเมื่อ',
    adm_revenue_contribution: 'สัดส่วนรายได้',
    adm_monthly_performance_log: 'บันทึกสรุปผลงานรายวันประจำเดือน',
    adm_monthly_desc: 'รายละเอียดการขายและจำนวนชิ้นที่ขายได้ในแต่ละวันของเดือน',
    adm_manage_orders: 'จัดการรายการสั่งซื้อจากลูกค้า',
    adm_pay_verify: 'ตรวจสอบการชำระเงิน',
    adm_ship_status: 'สถานะการจัดส่ง',
    adm_order_id: 'เลขออเดอร์',
    adm_customer: 'ลูกค้า',
    adm_date: 'วันที่',
    adm_total: 'ยอดรวม',
    adm_status: 'สถานะ',
    adm_slip_check: 'ตรวจสลิป',
    adm_actions: 'จัดการ',
    adm_no_orders: 'ไม่พบรายการที่ตรงตามที่เลือก',
    adm_order_details: 'รายละเอียดคำสั่งซื้อ',
    adm_cust_info: 'ข้อมูลลูกค้าและที่อยู่จัดส่ง',
    adm_items: 'รายการสินค้า',
    adm_total_pay: 'ยอดชำระรวม',
    adm_curr_status: 'สถานะปัจจุบัน',
    adm_reason: 'เหตุผล',
    adm_reason_label: 'เหตุผลในการยกเลิก',
    adm_wait_confirm: 'รอการยืนยันรับสินค้าจากลูกค้า',
    adm_finalized: 'เสร็จสมบูรณ์',
    adm_refund_success: 'คืนเงินสำเร็จ',
    adm_pending: 'รอดำเนินการ',
    adm_shipped: 'จัดส่งแล้ว',
    adm_arrived: 'ถึงที่หมาย',
    adm_completed: 'สำเร็จแล้ว',
    adm_cancelled: 'ยกเลิก',
    adm_refunded: 'คืนเงินแล้ว',
    adm_map_expand: 'ขยายแผนที่',
    adm_confirm_ship: 'ยืนยันการจัดส่ง',
    adm_confirm_ship_msg: 'คุณต้องการเปลี่ยนสถานะเป็น "จัดส่งแล้ว" ใช่หรือไม่?',
    adm_confirm_arrived: 'ยืนยันสินค้าถึงที่หมาย',
    adm_confirm_arrived_msg: 'คุณต้องการแจ้งว่าสินค้าถึงพิกัดที่หมายแล้วใช่หรือไม่?',
    adm_cancel_order: 'ยกเลิกคำสั่งซื้อ',
    adm_cancel_reason_ph: 'เช่น สินค้าหมด, ข้อมูลไม่ถูกต้อง...',
    adm_cancel_notice: 'ระบบจะส่งข้อความแจ้งเตือนเหตุผลนี้ให้ลูกค้าทราบ',
    adm_confirm_refund: 'ยืนยันการคืนเงินสำเร็จ',
    adm_confirm_refund_msg: 'คุณได้ทำการโอนเงินคืนให้ลูกค้าแล้วใช่หรือไม่?',
    adm_no_coords: 'ไม่พบข้อมูลพิกัดบนแผนที่ (ลูกค้ายังไม่ได้ปักหมุดที่อยู่)',
    adm_coords: 'พิกัด',
    adm_slip_view_hint: 'ส่องดูรูปสลิป',
    adm_verified_hint: 'อนุมัติแล้ว',
    adm_pending_hint: 'รอยืนยัน',
    adm_no_slip: 'ไม่มีสลิป',
    adm_map_pos_label: 'ตำแหน่งบนแผนที่',
    adm_not_specified: 'ยังไม่ได้ระบุ',
    adm_refund_info: 'ข้อมูลการคืนเงิน',
    h_bank: 'ธนาคาร',
    h_acc_name: 'ชื่อบัญชี',
    h_acc_num: 'เลขที่บัญชี',
    view_detail: 'ดูรายละเอียด',
    nav_wishlist: 'รายการโปรด',
    nav_under: 'ต่ำกว่า',
    nav_up: 'ขึ้นไป',
    nav_user_acc: 'บัญชีผู้ใช้',
    h_out_of_stock: 'สินค้าหมด',
    pay_summary: 'สรุปคำสั่งซื้อ',
    pay_missing_address: 'กรุณากรอกที่อยู่จัดส่งก่อนชำระเงิน',
    pay_missing_slip: 'กรุณาแนบสลิปหลักฐานการโอน',
    pay_select_shipping: 'กรุณาเลือกวิธีการจัดส่ง',

    
    auth_welcome: 'ยินดีต้อนรับกลับมา',
    auth_sign_in_desc: 'เข้าสู่ระบบบัญชีของคุณ',
    auth_create_acc: 'สร้างบัญชี',
    auth_join_desc: 'เข้าร่วมระบบ Velin Inventory',
    auth_username: 'ชื่อผู้ใช้',
    auth_password: 'รหัสผ่าน',
    auth_confirm_password: 'ยืนยันรหัสผ่าน',
    auth_email: 'อีเมล',
    auth_register_now: 'สมัครสมาชิกตอนนี้',
    auth_already_acc: 'มีบัญชีอยู่แล้ว?',
    auth_sign_in: 'เข้าสู่ระบบ',
    auth_register: 'สมัครสมาชิก',
    auth_back_home: 'กลับสู่เว็บไซต์',
    auth_dont_have_acc: "ยังไม่มีบัญชีใช่ไหม?",
    auth_login_success: 'ยินดีต้อนรับกลับมา',
    auth_reg_success: 'สมัครสมาชิกสำเร็จ! กรุณาเข้าสู่ระบบ',
    auth_pass_mismatch: 'รหัสผ่านไม่ตรงกัน',
    auth_conn_error: 'ข้อผิดพลาดในการเชื่อมต่อ',
    auth_login_failed: 'เข้าสู่ระบบล้มเหลว',
    auth_reg_failed: 'สมัครสมาชิกล้มเหลว',

    
    en: 'อังกฤษ',
    th: 'ไทย',
    in: 'นิ้ว',
    cm: 'ซม.',
    '2d': '2D',
    brand: 'แบรนด์',
    type: 'ประเภท',
    category: 'หมวดหมู่',
    sort: 'จัดเรียง',
    sale: 'ลดราคา',
    cart_shipping_pending: 'โปรดระบุที่อยู่จัดส่งก่อน',
    week: 'สัปดาห์',
    month: 'เดือน',
    f_tagline: 'จุดหมายปลายทางชั้นนำสำหรับการคัดสรรและสินค้าหายาก',

    
    super_admin_welcome: 'ยินดีต้อนรับ!',
    super_admin_desc_1: 'คุณเข้าสู่ระบบในฐานะ',
    super_admin_desc_2: 'กรุณาเลือกระบบที่คุณต้องการเข้าใช้งาน:',
    super_admin_btn_products: 'จัดการสินค้า/ออเดอร์ (ระบบปกติ)',
    super_admin_btn_admins: 'จัดการแอดมิน (ต้องสแกนใบหน้า)',

    
    adm_logs_title: 'ประวัติการใช้งานระบบ',
    adm_logs_desc: 'ตรวจจับและบันทึกทุกการเคลื่อนไหวของแอดมิน ทั้งการจัดการสินค้า อัปเดตสต๊อก และระบบออเดอร์ทั้งหมด',
    adm_logs_th_datetime: 'วันเวลา',
    adm_logs_th_admin: 'แอดมิน',
    adm_logs_th_action: 'การกระทำ',
    adm_logs_th_target: 'เป้าหมาย',
    adm_logs_th_entity: 'ไอดีอ้างอิง',
    adm_logs_th_details: 'รายละเอียด',
    adm_logs_no_activity: 'ไม่มีประวัติการใช้งานล่าสุด',
    adm_logs_loading: 'กำลังโหลดประวัติการใช้งาน...',

    
    adm_role_super: 'ผู้ดูแลระดับสูง',

    
    adm_loading_best_sellers: 'กำลังโหลดข้อมูลสินค้าขายดี...',
    adm_top_products_showcase: 'แสดงผลสินค้ายอดฮิต',
    adm_print_hub_report: 'พิมพ์รายงานการขาย',
    adm_units_sold: 'ชิ้นที่ขายได้',
    adm_units: 'ชิ้น',
    adm_revenue_label: 'รายได้:',
    adm_top_performance: 'ประสิทธิภาพสูงสุด',
    adm_full_catalog_performance: 'ประสิทธิภาพแคตตาล็อกทั้งหมด (จัดอันดับตามยอดขาย)',
    adm_no_sales_data: 'ยังไม่มีข้อมูลการขายบันทึกไว้',
    adm_rank: 'อันดับ',
    adm_product_id: 'รหัสสินค้า',
    adm_product_details: 'รายละเอียดสินค้า',
    adm_category: 'หมวดหมู่',
    adm_sales_volume: 'จำนวนที่ขาย',
    adm_revenue_gross: 'รายได้ (รวม)',
    adm_sold: 'ขายแล้ว',
    adm_status_peak: 'สูงสุด',
    adm_status_top_tier: 'ระดับบน',
    adm_status_stable: 'คงที่',
    adm_prev: 'ก่อนหน้า',
    adm_next: 'ถัดไป',

    
    adm_overview: 'ภาพรวม',
    adm_forecast_7_days: 'พยากรณ์ (7 วันล่าสุด)',
    adm_trend_year: 'แนวโน้มสำหรับปี',
    adm_low_stock_alerts: 'การแจ้งเตือนสต๊อกต่ำ',
    adm_by_size: 'ตามไซส์',
    adm_by_total: 'ตามทั้งหมด',
    adm_all_stock_sufficient: 'สต๊อกสินค้าทั้งหมดเพียงพอแล้ว',
    adm_sold_lower: 'ขายแล้ว',
    adm_daily_performance: 'ผลงานรายวัน',
    adm_revenue_target: 'เป้าหมายรายได้:',
    adm_order_volume: 'ปริมาณออเดอร์:',
    adm_lifetime_analytics: 'การวิเคราะห์ตลอดชีพ',
    adm_gross_revenue: 'รายได้รวม:',
    adm_inventory_velocity: 'ความเร็วในการขายสินค้า:',
    adm_items_sold: 'ชิ้นที่ขายได้',
    adm_lifetime_desc: 'ข้อมูลเชิงลึกแบบครบวงจรตลอดทุกรอบการดำเนินงาน อัตราการเติบโตและการหมุนเวียนสินค้าถูกเปรียบเทียบกับผลงานในอดีต',

    
    adm_status_pending: 'รอดำเนินการ',
    adm_status_shipped: 'จัดส่งแล้ว',
    adm_status_arrived: 'ถึงที่หมาย',
    adm_status_delivered: 'สำเร็จแล้ว',
    adm_status_cancelled: 'ยกเลิก',
    adm_status_refunded: 'คืนเงิน',
    adm_shipping_status: 'สถานะการจัดส่ง',


    
    adm_manage_products: 'จัดการสินค้า',
    adm_filter: 'ตัวกรอง',
    adm_total_low: 'สต็อก < 5',
    adm_size_low: 'ไซส์ < 5',
    adm_search_products: 'ค้นหาสินค้า...',
    adm_add_product: '+ เพิ่มสินค้า',
    adm_table_image: 'รูปภาพ',
    adm_table_code: 'รหัส',
    adm_table_name: 'ชื่อสินค้า',
    adm_table_category: 'หมวดหมู่',
    adm_table_brand: 'แบรนด์',
    adm_table_price: 'ราคา',
    adm_table_discount: 'ส่วนลด',
    adm_table_final_price: 'ราคาสุทธิ',
    adm_table_sizes: 'ไซส์',
    adm_table_stock: 'สต๊อก',
    adm_table_actions: 'จัดการ',
    adm_export_pdf: 'ส่งออก PDF',
    adm_financial_summary: 'สรุปข้อมูลการเงิน',
    adm_all_orders: 'ออเดอร์ทั้งหมด',
    adm_pending_check: 'รอยืนยันสลิป',
    adm_verified_only: 'ยืนยันสลิปแล้ว',
    adm_bank_notified: 'แจ้งเลขบัญชีแล้ว',
    adm_edit_product: 'แก้ไขสินค้า',
    adm_add_color: 'เพิ่มสีสินค้า',
    adm_form_name: 'ชื่อสินค้า',
    adm_form_code: 'รหัสสินค้า',
    adm_form_price: 'ราคา (฿)',
    adm_form_discount: 'ส่วนลด (%)',
    adm_form_category: 'หมวดหมู่',
    adm_form_brand: 'แบรนด์',
    adm_form_desc: 'รายละเอียด',
    adm_form_gallery: 'จัดการคลังรูปภาพ',
    adm_form_cover: 'หน้าปก',
    adm_form_stock: 'สต๊อก',
    adm_form_size_guide: 'ตารางไซส์',
    adm_form_chest_label: 'รอบอก',
    adm_form_length_label: 'ความยาว',
    adm_form_add_stock: '+ เพิ่มสต๊อก',
    adm_form_add_guide: '+ เพิ่มตารางไซส์',
    adm_form_save: 'บันทึกการเปลี่ยนแปลง',
    adm_form_cancel: 'ยกเลิก',
    adm_form_add_photos: '+ เพิ่มรูปภาพ',
    adm_print_report: 'พิมพ์รายงาน PDF',

    adm_page_label: 'หน้า:',
    adm_page: 'หน้า',
    adm_of: 'จาก',

    adm_loading_product_details: 'กำลังโหลดรายละเอียดสินค้า...',
    adm_variants_colors: 'รุ่นอื่นๆ / สีอื่นๆ',
    adm_available_sizes: 'ไซส์ที่พร้อมจำหน่าย',
    adm_product_details_section: 'ข้อมูลสินค้า',
    adm_no_description: 'ไม่มีคำบรรยายสำหรับสินค้านี้',
    adm_size_guide_title: 'ตารางเทียบไซส์',
    adm_customer_reviews: 'รีวิวจากลูกค้า',
    adm_no_reviews: 'ยังไม่มีความคิดเห็นสำหรับสินค้านี้',
    adm_edit_product_details: 'แก้ไขข้อมูลสินค้า',
    adm_product_name: 'ชื่อสินค้า',
    adm_manage_gallery_desc: 'จัดการรูปภาพ (รูปแรกคือรูปปก, ใช้ ◀ ▶ เพื่อจัดลำดับ)',
    adm_add_photos: 'เพิ่มรูปภาพ',
    adm_code_label: 'รหัสสินค้า:',
    adm_category_label: 'หมวดหมู่:',
    adm_in_stock: 'มีสินค้าในสต็อก',
    adm_out_of_stock: 'สินค้าหมด',
    adm_units_left: 'ชิ้น',
    adm_all_sizes: 'ทุกไซส์',
    adm_ship: 'จัดส่ง',
    adm_arrive: 'ถึงที่หมาย',
    adm_workforce_mgmt: 'การจัดการบุคลากร',
    adm_workforce_desc: 'การจัดการความปลอดภัยและกำหนดสิทธิ์ผู้ใช้งาน',
    adm_total_personnel: 'จำนวนบุคลากรทั้งหมด',
    adm_super_admins: 'ซูเปอร์แอดมิน',
    adm_biometrics_registered: 'ลงทะเบียนใบหน้าแล้ว',
    adm_personnel_access_list: 'รายชื่อบุคลากรผู้มีสิทธิ์เข้าถึง',
    adm_personnel_access_desc: 'รายชื่อแอดมินและระดับสิทธิ์การเข้าถึงระบบทั้งหมด',
    adm_add_new_admin: 'เพิ่มแอดมินใหม่',
    adm_role_admin: 'ผู้ดูแลระบบ (Admin)',
    adm_role_superadmin: 'ผู้ดูแลสูงสุด (Super Admin)',
    adm_no_email_provided: 'ไม่มีข้อมูลอีเมล',
    adm_table_personnel: 'บุคลากร',
    adm_table_permissions: 'สิทธิ์การเข้าถึง',
    adm_table_biometrics: 'ข้อมูลใบหน้า',
    adm_table_management: 'จัดการ',
    adm_biometrics_required: 'จำเป็น',
    adm_biometrics_registered_badge: 'ลงทะเบียนแล้ว',
    adm_biometrics_standard: 'มาตรฐาน',
    adm_initiate_scan: 'เริ่มการสแกนใบหน้า',
    adm_active_biometric_login: 'เปิดใช้งานการล็อกอินด้วยใบหน้า',
    adm_update_rescan: 'อัปเดต / สแกนใบหน้าใหม่',
    adm_create_access_token: 'สร้างรหัสการเข้าถึง',
    adm_update_credentials: 'อัปเดตข้อมูลการเข้าถึง',
    adm_superadmin_face_required: 'ไม่สามารถปรับเป็น Super Admin ได้: กรุณาลงทะเบียนใบหน้าก่อนครับ',
    adm_security_req: 'ข้อกำหนดด้านความปลอดภัย',
    adm_reset_face_error: 'เกิดข้อผิดพลาดในการรีเซ็ตข้อมูลใบหน้า',
    adm_reset_biometrics: 'รีเซ็ตข้อมูลใบหน้า',
    adm_reset_face_data: 'รีเซ็ตข้อมูลใบหน้า',
    adm_scan_face_now: 'สแกนใบหน้าเดี๋ยวนี้',
    edit: 'แก้ไข',
    delete: 'ลบ',
    adm_admin_updated: 'อัปเดตข้อมูลแอดมินเรียบร้อยแล้ว',
    adm_admin_added: 'เพิ่มแอดมินใหม่เรียบร้อยแล้ว',
    adm_confirm_delete: 'ยืนยันการลบ',
    adm_delete_admin_confirm: 'คุณแน่ใจหรือไม่ที่จะลบเจ้าหน้าที่คนนี้ออกจากระบบ? การดำเนินการนี้ไม่สามารถย้อนกลับได้',
    adm_reset_face_confirm: 'คุณแน่ใจหรือไม่ที่จะรีเซ็ตข้อมูลใบหน้าของ {{username}}? เจ้าหน้าที่จะต้องสแกนใบหน้าใหม่',
    adm_reset_success: 'รีเซ็ตข้อมูลใบหน้าเรียบร้อยแล้ว',
    adm_form_password: 'รหัสผ่านสำหรับการเข้าถึง',

  }
};

export const LanguageProvider = ({ children }) => {
  const { user } = useContext(AuthContext);
  
  
  const getLangKey = (u) => {
    if (u && u.id) return `velin_lang_${u.id}`;
    return 'velin_lang_guest';
  };

  
  const [language, setLanguage] = useState(() => {
    try {
      const storedUser = JSON.parse(localStorage.getItem('user'));
      const key = storedUser ? `velin_lang_${storedUser.id}` : 'velin_lang_guest';
      return localStorage.getItem(key) || 'en';
    } catch {
      return 'en';
    }
  });

  
  useEffect(() => {
    const syncLanguage = async () => {
      const key = getLangKey(user);
      const localPref = localStorage.getItem(key);

      
      
      if (localPref) {
        setLanguage(localPref);
      } else {
        
        setLanguage('en');
      }

      
      if (user) {
        try {
          const res = await api.get('/auth/profile');
          if (res.data && res.data.preferred_language) {
            setLanguage(res.data.preferred_language);
            localStorage.setItem(key, res.data.preferred_language);
          }
        } catch (err) {
          console.error("Failed to fetch language from DB");
        }
      }
    };
    
    syncLanguage();
  }, [user?.id]);

  const toggleLanguage = async (lang) => {
    setLanguage(lang);
    const key = getLangKey(user);
    localStorage.setItem(key, lang);
    
    
    if (user) {
      try {
        await api.put('/auth/profile', { preferred_language: lang });
      } catch (err) {
        console.error("Failed to sync language to DB");
      }
    }
  };

  const t = (key, params = {}) => {
    let text = translations[language]?.[key] || key;
    if (typeof text === 'string') {
      Object.keys(params).forEach(param => {
        text = text.replace(`{{${param}}}`, params[param]);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
